server:
  port: 9099

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.94.143:3306/blogdemo?useSSL=false
    username: root
    password: Xlz111!@#
    maxActive: 10
    maxWait: 50000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false


  mvc:
    static-path-pattern: static/**
  thymeleaf:
    cache: false
    encoding: utf-8


picfile:
  path: nopath
